### ISSUE TITLE
filtr nabídky

### ISSUE THREAD

**Issue by Karubin** [nkp-osf/VDK#14]
při nastavení filtru pouze nabídky se nezobrazují žádné výsledky, ačkoliv nabídky jiných knihoven existují a zároveň se tituly z těchto nabídek zobrazují na hlavní stránce

**Comment by Karubin** [comment]
dnes při opakovaném zkoušení filtr nabídky funguje.

**Comment by albertoh** [comment]
Muzeme zavrit?

**Comment by Karubin** [comment]
Momentálně se nelze do VDK přihlásit (error 500), nemůžu tedy ověřit funkčnost

**Comment by Karubin** [comment]
při opakovaném zkoušení se nabídky zobrazují korektně - asi je možné uzavřít
