### ISSUE TITLE
konkrétní exemplář v nabídce

### ISSUE THREAD

**Issue by Karubin** [nkp-osf/VDK#15]
Bylo by vhodné, kdyby byl při nabízení zvýrazněn konkrétní exemplář - zvlášť u vícesvazkových titulů, kde nemusí být zřejmé, který svazek je nabízen
![image](https://cloud.githubusercontent.com/assets/14339355/20247259/299456b4-a9c8-11e6-883f-2812d5dc7556.png)

**Comment by albertoh** [comment]
melo by se objevit obarvit danni radek, a pri najeti na nazev nabidky orameckovat

**Comment by Karubin** [comment]
vše funguje, issue lze uzavřít
