### ISSUE TITLE
nabídkla z csv

### ISSUE THREAD

**Issue by Karubin** [nkp-osf/VDK#16]
při vytváření nabídky z exportu nelze u jednotlivých titulů nastavit cenu

**Comment by albertoh** [comment]
Je to mozne kdyz do csv pridate pro kazdy radek cenu a poznamku, sloupce 10 a 11.
Seznam sloupcu v csv je:
isbn issn ccnb 245a 245n 245p 250a 100a 110a 111a 260a cena comment

**Comment by Karubin** [comment]
funguje bezchybně, issue je možné uzavřít
