### ISSUE TITLE
zamrzání vdk

### ISSUE THREAD

**Issue by Karubin** [nkp-osf/VDK#20]
aplikace občas přestane úplně reagovat a následně nejde ani znovu načíst - občas to trvá i desítky minut. Stává se to pouze, pokud je přihlášený uživatel. Nevšiml jsem si, že by se to stávalo při jedné konkrétní akci (pokud ano, přidám komentář)

**Comment by albertoh** [comment]
Nemuzu reprodukovat. Muze to souvisit se serverem.
Bude novy server
