### ISSUE TITLE
faseta počet dokumentů nefunguje

### ISSUE THREAD

**Issue by zabak** [nkp-osf/VDK#22]
např. http://vdk.nkp.cz/vdk/?offset=0&hits=&q=&title_suggest=&fq=bohemika%3A"true"&fq=status%3A"Z"&zdroj=RF&zdroj=UKF&zdroj=NKF&title=&author=&rok=&isbn=&issn=&ccnb=&vydavatel=&fq=pocet_exemplaru%3A"1"
vrací 0 záznamů
přitom http://vdk.nkp.cz/vdk/?offset=0&hits=&q=&title_suggest=&fq=bohemika%3A"true"&fq=status%3A"Z"&zdroj=RF&zdroj=UKF&zdroj=NKF&title=&author=&rok=&isbn=&issn=&ccnb=&vydavatel=
ukazuje, že by takových mělo být přes 7000

**Comment by albertoh** [comment]
Nemuzu reprodukovat. (pozor, vyse uvedene url nema posledni uvozovku)
