### ISSUE TITLE
Při zvolení filtru ztráta se zobrazí titul bez ztráty

### ISSUE THREAD

**Issue by zabak** [nkp-osf/VDK#24]
Např. http://vdk.nkp.cz/vdk/?offset=0&hits=&q=&title_suggest=&fq=status%3A"Z"&title=&author=&rok=&isbn=&issn=&ccnb=&vydavatel=

(třetí titul v seznamu: Přichází puberta : Sexuální výchova od 10 do 13 let   )

**Comment by albertoh** [comment]
Nemuzu reprodukovat. Vsechny tituly maji exemplar se ztratou.

http://vdk.nkp.cz/vdk/?offset=0&hits=&q=puberta+&title_suggest=&fq=status%3A%22Z%22&title=&author=&rok=&isbn=&issn=&ccnb=&vydavatel=

**Comment by zabak** [comment]
Asi pomohla nějaká reindexace, je možné zavřít.
