### ISSUE TITLE
Záznamy, které nemají exempláře

### ISSUE THREAD

**Issue by zabak** [nkp-osf/VDK#37]
http://vdk.nkp.cz/vdk/?offset=0&hits=&q=krok+za+krokem+gellner&title_suggest=&title=&author=&rok=&isbn=&issn=&ccnb=&vydavatel=&fq=pocet_exemplaru%3A%220%22

U těchto záznamů není uveden žádný exemplář. Vzhledem k tomu se na ně nedá ani kliknout a zobrazit si celý záznam. Není tak jasné proč tam jsou, když se ani nezdeduplikovaly ani nic jiného. prostě jsou. Nevíme o nich ani z jaké knihovny pocházejí. To poslední by mohlo vyřešit #28, ale otázka je, jestli to není spíš příznak že se do indexu dostalo nějaké smetí.

**Comment by zabak** [comment]
Teď koukám, že po přihlášení tam možnost zobrarzit bib. záznam je a že ony záznamy přišly z VKOL, asi mají chybu v nastavení OAI nebo něco.

**Comment by albertoh** [comment]
Bude doreseno pri aktualizaci rozhrani

**Comment by lucka-pavlova** [comment]
Přicházejí v rámci setu. Možno upravit indexaci, aby je ignorovala.

**Comment by jiri-spacil** [comment]
Ten zaznam je ve VKOL zruseny od roku 2015, viz https://aleph.vkol.cz/OAI?verb=GetRecord&identifier=oai:aleph.vkol.cz:SVK01_VKOLOAI-000077736&metadataPrefix=marc21, zda se, ze se zaznam ve VDK neaktualizoval. Navic me zarazi, ze se jedna jeste o set VKOLOAI, protoze loni jsme menili s pane Hernandezem za dedikovany set primo pro VDK (SVK-VDK). Nemohl tam zustat ten stary set, pripadne nejake jeho pozustatky?

**Comment by albertoh** [comment]
Nechame je tam
