### ISSUE TITLE
Přidávání titulu do nabídky

### ISSUE THREAD

**Issue by Karubin** [nkp-osf/VDK#5]
Při přidávaní titulu do nabídky skrze šablonu a zmáčknutí tlačítka "přídat do nabídky" na spodním okraji šablony se přidá jiný titul, než který byl zadán do šablony (přidal se titul z minulého vyhledávání).

**Comment by albertoh** [comment]
Muzete mi popsat presny postup? Nemuzu se k tomu chovani dostat

**Comment by Karubin** [comment]
Pridal jsem skrze sablonu nektery titul (nasledne ho z nabidky vymazal) pak jsem vyhledal v sablone jiny a po kliku na spodni tlacitko "pridat do nabidky" se pridal predchozi titul (totez se stane, necham-li sablonu prazdnou)
viz https://youtu.be/ty1Lf78Ofhk

**Comment by Karubin** [comment]
chyba se již neopakovala - možné uzavřít
