### ISSUE TITLE
Filtr: stav ve zdroji

### ISSUE THREAD

**Issue by Karubin** [nkp-osf/VDK#8]
Bylo by potřeba vytvořit nový filtr "stav ve zdroji" (např. stav vyřazeno ve zdroji NKF)

**Comment by Karubin** [comment]
aktuálně lze aplikovat filtr (přes ikonku štítku) pouze na již zobrazené výsledky - tj. skryjí se exempláře s jiným stavem (resp. zdrojem), než který je vybrán. Ideální stav by byl filtr "zdroj && stav" - tj. kumulativní splnění podmínek zdroje a stavu u exempláře, nikoliv v rámci titulu.

Příklad viz obrázek: nastavení filtru zdroj UKF; stav absenčně - nalezený titul sice splňuje obě podmínky, ale žádný z exemplářu ne. Vyhledávání exemplářů v konkrétním zdroji s konkrétním stavem je důležitou funkcí.

![image](https://cloud.githubusercontent.com/assets/14339355/21310556/332d8628-c5e3-11e6-9257-2e29953bd387.png)

**Comment by albertoh** [comment]
Takova funkcionalita vyzaduje novou strukturu indexu.
Soucasny index ma jako zaklad titul, nikoli exemplar. Hladame tituly, a v ramci titulu ukazujeme examplare.
Pokud vyhledavani se musi chovat jak popsano, hledat exemplare, potom collapsovani exemplaru pri hledani bude vyrazne zpomalit aplikaci.
  Jestli jen chceme moznost kombinaci zdroj a stav, mozno to vyresit i pri soucasne strukture, tj hledani titulu. V tomto pipade je nutne pridat nove pole, a reindexovat vsechno.
